import { sql } from "drizzle-orm";
import { index, integer, primaryKey, doublePrecision, pgTable, boolean, timestamp, date, jsonb, check, text, uniqueIndex } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string", precision: 3 }).notNull() };

export const vendors = pgTable("vendors", { id: text("id").primaryKey(), name: text("name").notNull(), homepageUrl: text("homepage_url"), ...timestamps });

export const products = pgTable("products", { id: text("id").primaryKey(), vendorId: text("vendor_id").notNull().references(() => vendors.id), name: text("name").notNull(), family: text("family"), ...timestamps }, (table) => [uniqueIndex("idx_products_vendor_name").on(table.vendorId, table.name), index("idx_products_vendor_family_name").on(table.vendorId, table.family, table.name)]);

export const productVersions = pgTable("product_versions", { id: text("id").primaryKey(), productId: text("product_id").notNull().references(() => products.id), version: text("version").notNull(), release: text("release"), ...timestamps }, (table) => [uniqueIndex("idx_product_versions_product_version").on(table.productId, table.version)]);

export const sources = pgTable("sources", { id: text("id").primaryKey(), vendorId: text("vendor_id").references(() => vendors.id), name: text("name").notNull(), kind: text("kind").notNull(), discoveryUrl: text("discovery_url").notNull(), enabled: boolean("enabled").notNull().default(true), readiness:text("readiness").notNull().default("validating"), readinessReason:text("readiness_reason"), retryAfter:timestamp("retry_after",{withTimezone:true,mode:"string"}), ...timestamps });

export const sourceRuns = pgTable("source_runs", {
  id: text("id").primaryKey(), sourceId: text("source_id").notNull().references(() => sources.id), idempotencyKey: text("idempotency_key"), startedAt: timestamp("started_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true, mode: "string", precision: 3 }), status: text("status").notNull(), ingestionMode: text("ingestion_mode").notNull().default("delta"), windowStart: timestamp("window_start", { withTimezone: true, mode: "string", precision: 3 }), windowEnd: timestamp("window_end", { withTimezone: true, mode: "string", precision: 3 }), continuationIn: text("continuation_in"), continuationOut: text("continuation_out"), checkpointId: text("checkpoint_id"), maxItems: integer("max_items").notNull().default(12), boundHit: boolean("bound_hit").notNull().default(false), datasetDate: timestamp("dataset_date", { withTimezone: true, mode: "string", precision: 3 }), sourceHash: text("source_hash"), recordsDiscovered: integer("records_discovered").notNull().default(0), recordsInserted: integer("records_inserted").notNull().default(0), recordsChanged: integer("records_changed").notNull().default(0), recordsUnchanged: integer("records_unchanged").notNull().default(0), recordsFailed: integer("records_failed").notNull().default(0), errorSummary: text("error_summary"),
}, (table) => [index("idx_source_runs_source_started").on(table.sourceId, table.startedAt), index("idx_source_runs_status_completed").on(table.status, table.completedAt), index("idx_source_runs_checkpoint").on(table.checkpointId, table.startedAt), uniqueIndex("idx_source_runs_idempotency").on(table.sourceId, table.idempotencyKey)]);

export const sourceRunResults = pgTable("source_run_results", { id: text("id").primaryKey(), sourceRunId: text("source_run_id").notNull().references(() => sourceRuns.id), sourceRef: text("source_ref").notNull(), status: text("status").notNull(), changeTypesJson: jsonb("change_types_json").notNull().default([]), errorSummary: text("error_summary"), durationMs: integer("duration_ms").notNull().default(0), observedAt: timestamp("observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull() }, (table) => [index("idx_source_run_results_run").on(table.sourceRunId)]);

export const releaseEvents = pgTable("release_events", { id: text("id").primaryKey(), vendorId: text("vendor_id").notNull().references(() => vendors.id), eventType: text("event_type").notNull(), eventDate: date("event_date", { mode: "string" }).notNull(), label: text("label").notNull(), sourceUrl: text("source_url"), reportedCveCount: integer("reported_cve_count"), reportedAt: timestamp("reported_at", { withTimezone: true, mode: "string", precision: 3 }), reportedProductFamiliesJson: jsonb("reported_product_families_json"), ...timestamps }, (table) => [uniqueIndex("idx_release_events_vendor_type_date").on(table.vendorId, table.eventType, table.eventDate), index("idx_release_events_type_date").on(table.eventType, table.eventDate)]);

export const advisories = pgTable("advisories", {
  id: text("id").primaryKey(), vendorId: text("vendor_id").notNull().references(() => vendors.id), sourceId: text("source_id").notNull().references(() => sources.id), vendorAdvisoryId: text("vendor_advisory_id").notNull(), title: text("title").notNull(), summary: text("summary"), sourceUrl: text("source_url").notNull(), publishedAt: timestamp("published_at", { withTimezone: true, mode: "string", precision: 3 }), sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true, mode: "string", precision: 3 }), withdrawnAt: timestamp("withdrawn_at", { withTimezone: true, mode: "string", precision: 3 }), ...timestamps,
}, (table) => [uniqueIndex("idx_advisories_vendor_advisory").on(table.vendorId, table.vendorAdvisoryId), index("idx_advisories_published").on(table.publishedAt), index("idx_advisories_vendor_published").on(table.vendorId, table.publishedAt), index("idx_advisories_modified").on(table.sourceUpdatedAt)]);

export const releaseEventAdvisories = pgTable("release_event_advisories", { releaseEventId: text("release_event_id").notNull().references(() => releaseEvents.id), advisoryId: text("advisory_id").notNull().references(() => advisories.id) }, (table) => [primaryKey({ columns: [table.releaseEventId, table.advisoryId] }), index("idx_release_event_advisories_advisory_event").on(table.advisoryId, table.releaseEventId)]);

export const advisoryRevisions = pgTable("advisory_revisions", {
  id: text("id").primaryKey(), advisoryId: text("advisory_id").notNull().references(() => advisories.id), sourceRunId: text("source_run_id").references(() => sourceRuns.id), observedAt: timestamp("observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), sourceUpdatedAt: timestamp("source_updated_at", { withTimezone: true, mode: "string", precision: 3 }), contentHash: text("content_hash").notNull(), affectedProductsHash: text("affected_products_hash").notNull(), remediationHash: text("remediation_hash").notNull(), exploitationStatus: text("exploitation_status").notNull(), vendorSeverity: text("vendor_severity"), cvssScore: doublePrecision("cvss_score"), changeTypesJson: jsonb("change_types_json").notNull(), normalizedJson: jsonb("normalized_json").notNull(), sourceUrl: text("source_url").notNull(),
}, (table) => [index("idx_advisory_revisions_advisory_hash").on(table.advisoryId, table.contentHash), index("idx_advisory_revisions_observed").on(table.observedAt), index("idx_advisory_revisions_advisory_observed").on(table.advisoryId, table.observedAt)]);

export const cves = pgTable("cves", { id: text("id").primaryKey(), description: text("description"), cwe: text("cwe"), cvssScore: doublePrecision("cvss_score"), cvssVector: text("cvss_vector"), publishedAt: timestamp("published_at", { withTimezone: true, mode: "string", precision: 3 }), modifiedAt: timestamp("modified_at", { withTimezone: true, mode: "string", precision: 3 }), canonicalSourceUrl: text("canonical_source_url"), recordStatus:text("record_status").notNull().default("unknown"), assessmentSource:text("assessment_source"), ...timestamps }, (table) => [index("idx_cves_published").on(table.publishedAt), index("idx_cves_cwe_published").on(table.cwe, table.publishedAt)]);

export const advisoryCves = pgTable("advisory_cves", { advisoryId: text("advisory_id").notNull().references(() => advisories.id), cveId: text("cve_id").notNull().references(() => cves.id), vendorDescription: text("vendor_description"), vendorCwe: text("vendor_cwe"), vendorSeverity: text("vendor_severity"), normalizedSeverity: text("normalized_severity").notNull(), vendorCvssScore: doublePrecision("vendor_cvss_score"), vendorCvssVector: text("vendor_cvss_vector") }, (table) => [primaryKey({ columns: [table.advisoryId, table.cveId] }), index("idx_advisory_cves_cve").on(table.cveId), index("idx_advisory_cves_severity").on(table.normalizedSeverity), index("idx_advisory_cves_severity_cve").on(table.normalizedSeverity, table.cveId)]);

export const affectedProducts = pgTable("affected_products", {
  id: text("id").primaryKey(), advisoryId: text("advisory_id").notNull().references(() => advisories.id), advisoryRevisionId: text("advisory_revision_id").notNull().references(() => advisoryRevisions.id), cveId: text("cve_id").references(() => cves.id), productId: text("product_id").notNull().references(() => products.id), affectedVersion: text("affected_version"), fixedVersion: text("fixed_version"), status: text("status").notNull(), sourceProductId: text("source_product_id"),
}, (table) => [index("idx_affected_products_advisory_revision").on(table.advisoryId, table.advisoryRevisionId), index("idx_affected_products_cve").on(table.cveId), index("idx_affected_products_product_cve_revision").on(table.productId, table.cveId, table.advisoryRevisionId), index("idx_affected_products_revision_cve_product").on(table.advisoryRevisionId, table.cveId, table.productId)]);

export const remediations = pgTable("remediations", {
  id: text("id").primaryKey(), advisoryId: text("advisory_id").notNull().references(() => advisories.id), advisoryRevisionId: text("advisory_revision_id").notNull().references(() => advisoryRevisions.id), cveId: text("cve_id").references(() => cves.id), productId: text("product_id").references(() => products.id), kind: text("kind").notNull(), patchAvailable: boolean("patch_available"), fixedVersion: text("fixed_version"), action: text("action"), rebootRequired: boolean("reboot_required"), superseded: boolean("superseded"), sourceUrl: text("source_url").notNull(), publishedAt: timestamp("published_at", { withTimezone: true, mode: "string", precision: 3 }), updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string", precision: 3 }),
}, (table) => [index("idx_remediations_cve").on(table.cveId), index("idx_remediations_advisory_revision").on(table.advisoryId, table.advisoryRevisionId), index("idx_remediations_state_cve_revision").on(table.patchAvailable, table.kind, table.cveId, table.advisoryRevisionId), index("idx_remediations_revision_cve_kind").on(table.advisoryRevisionId, table.cveId, table.kind)]);

export const cveDashboardFacts = pgTable("cve_dashboard_facts", {
  cveId: text("cve_id").primaryKey().references(() => cves.id), title: text("title").notNull(), vendor: text("vendor").notNull(), vendorIds: text("vendor_ids").notNull(), product: text("product"), severityRank: integer("severity_rank").notNull(), cvss: doublePrecision("cvss"), epss: doublePrecision("epss"), epssPercentile: doublePrecision("epss_percentile"), kev: boolean("kev").notNull(), knownExploited: boolean("known_exploited").notNull(), zeroDay: boolean("zero_day").notNull(), patchAvailable: boolean("patch_available"), mitigationAvailable: boolean("mitigation_available").notNull(), workaroundAvailable: boolean("workaround_available").notNull(), publishedAt: timestamp("published_at", { withTimezone: true, mode: "string", precision: 3 }), modifiedAt: timestamp("modified_at", { withTimezone: true, mode: "string", precision: 3 }), cwe: text("cwe"), priority: text("priority").notNull(), projectedAt: timestamp("projected_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(),
}, (table) => [index("idx_dashboard_facts_priority_sort").on(table.priority, table.severityRank, table.epssPercentile, table.publishedAt, table.cveId), index("idx_dashboard_facts_severity_cvss").on(table.severityRank, table.cvss), index("idx_dashboard_facts_epss").on(table.epssPercentile), index("idx_dashboard_facts_published").on(table.publishedAt), index("idx_dashboard_facts_modified").on(table.modifiedAt), index("idx_dashboard_facts_threat").on(table.kev, table.knownExploited, table.zeroDay)]);

export const dashboardProjectionState = pgTable("dashboard_projection_state", { id: text("id").primaryKey(), projectionVersion: integer("projection_version").notNull(), generatedAt: timestamp("generated_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), sourceRunId: text("source_run_id"), cveCount: integer("cve_count").notNull(), status: text("status").notNull(), parityCheckedAt: timestamp("parity_checked_at", { withTimezone: true, mode: "string", precision: 3 }), parityStatus: text("parity_status"), parityJson: jsonb("parity_json"), lastAttemptAt: timestamp("last_attempt_at", { withTimezone: true, mode: "string", precision: 3 }), lastAttemptStatus: text("last_attempt_status"), lastAttemptError: text("last_attempt_error") });

export const cveDashboardFactsStaging = pgTable("cve_dashboard_facts_staging", {
  cveId: text("cve_id").primaryKey().references(() => cves.id), title: text("title").notNull(), vendor: text("vendor").notNull(), vendorIds: text("vendor_ids").notNull(), product: text("product"), severityRank: integer("severity_rank").notNull(), cvss: doublePrecision("cvss"), epss: doublePrecision("epss"), epssPercentile: doublePrecision("epss_percentile"), kev: boolean("kev").notNull(), knownExploited: boolean("known_exploited").notNull(), zeroDay: boolean("zero_day").notNull(), patchAvailable: boolean("patch_available"), mitigationAvailable: boolean("mitigation_available").notNull(), workaroundAvailable: boolean("workaround_available").notNull(), publishedAt: timestamp("published_at", { withTimezone: true, mode: "string", precision: 3 }), modifiedAt: timestamp("modified_at", { withTimezone: true, mode: "string", precision: 3 }), cwe: text("cwe"), priority: text("priority").notNull(), projectedAt: timestamp("projected_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(),
});

export const dashboardProjectionLeases = pgTable("dashboard_projection_leases", { id: text("id").primaryKey(), holder: text("holder").notNull(), acquiredAt: timestamp("acquired_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true, mode: "string", precision: 3 }).notNull() });

export const exploitEvidence = pgTable("exploit_evidence", {
  id: text("id").primaryKey(), cveId: text("cve_id").notNull().references(() => cves.id), advisoryId: text("advisory_id").references(() => advisories.id), sourceId: text("source_id").notNull().references(() => sources.id), evidenceType: text("evidence_type").notNull(), status: text("status").notNull(), evidenceDate: date("evidence_date", { mode: "string" }), evidenceUrl: text("evidence_url").notNull(), summary: text("summary"), firstObservedAt: timestamp("first_observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), lastObservedAt: timestamp("last_observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(),
}, (table) => [uniqueIndex("idx_exploit_evidence_identity").on(table.cveId, table.sourceId, table.evidenceType, table.evidenceUrl), index("idx_exploit_evidence_state_cve").on(table.evidenceType, table.status, table.cveId)]);

export const kevEntries = pgTable("kev_entries", {
  cveId: text("cve_id").primaryKey().references(() => cves.id), sourceRunId: text("source_run_id").references(() => sourceRuns.id), active: boolean("active").notNull(), dateAdded: date("date_added", { mode: "string" }).notNull(), dueDate: date("due_date", { mode: "string" }), requiredAction: text("required_action"), knownRansomwareCampaignUse: text("known_ransomware_campaign_use"), entryHash: text("entry_hash").notNull(), sourceUrl: text("source_url").notNull(), firstObservedAt: timestamp("first_observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), lastObservedAt: timestamp("last_observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), removedAt: timestamp("removed_at", { withTimezone: true, mode: "string", precision: 3 }),
}, (table) => [index("idx_kev_entries_active_due").on(table.active, table.dueDate)]);

export const epssDatasets = pgTable("epss_datasets", { scoreDate: date("score_date", { mode: "string" }).primaryKey(), sourceRunId: text("source_run_id").notNull().references(() => sourceRuns.id), modelVersion: text("model_version"), sourceHash: text("source_hash").notNull(), sourceUrl: text("source_url").notNull(), rowCount: integer("row_count").notNull(), matchedCveCount: integer("matched_cve_count").notNull(), status: text("status").notNull(), isCurrent: boolean("is_current").notNull().default(false), publishedAt: timestamp("published_at", { withTimezone: true, mode: "string", precision: 3 }).notNull() }, (table) => [index("idx_epss_datasets_current_date").on(table.isCurrent, table.scoreDate), uniqueIndex("idx_epss_one_current").on(table.isCurrent).where(sql`${table.isCurrent}`)]);

export const epssObservations = pgTable("epss_observations", { cveId: text("cve_id").notNull().references(() => cves.id), scoreDate: date("score_date", { mode: "string" }).notNull().references(() => epssDatasets.scoreDate), score: doublePrecision("score").notNull(), percentile: doublePrecision("percentile").notNull(), modelVersion: text("model_version"), sourceRunId: text("source_run_id").notNull().references(() => sourceRuns.id), observedAt: timestamp("observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull() }, (table) => [primaryKey({ columns: [table.cveId, table.scoreDate] }), check("epss_score_range", sql`${table.score} BETWEEN 0 AND 1 AND ${table.percentile} BETWEEN 0 AND 1`), index("idx_epss_observations_date").on(table.scoreDate), index("idx_epss_observations_cve_model_date").on(table.cveId, table.modelVersion, table.scoreDate)]);

export const intelligenceChanges = pgTable("intelligence_changes", {
  id: text("id").primaryKey(), sourceRunId: text("source_run_id").notNull().references(() => sourceRuns.id), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), cveId: text("cve_id").references(() => cves.id), advisoryId: text("advisory_id").references(() => advisories.id), changeType: text("change_type").notNull(), observedAt: timestamp("observed_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), beforeJson: jsonb("before_json"), afterJson: jsonb("after_json"), summary: text("summary").notNull(),
}, (table) => [index("idx_intelligence_changes_observed").on(table.observedAt), index("idx_intelligence_changes_cve").on(table.cveId), index("idx_intelligence_changes_type_observed_cve").on(table.changeType, table.observedAt, table.cveId), index("idx_intelligence_changes_cve_observed_type").on(table.cveId, table.observedAt, table.changeType)]);

export const ingestionLeases = pgTable("ingestion_leases", { sourceId: text("source_id").primaryKey().references(() => sources.id), holder: text("holder").notNull(), acquiredAt: timestamp("acquired_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true, mode: "string", precision: 3 }).notNull() });

export const ingestionCheckpoints = pgTable("ingestion_checkpoints", {
  id: text("id").primaryKey(), sourceId: text("source_id").notNull().references(() => sources.id), mode: text("mode").notNull(), coverageStart: timestamp("coverage_start", { withTimezone: true, mode: "string", precision: 3 }).notNull(), coverageEnd: timestamp("coverage_end", { withTimezone: true, mode: "string", precision: 3 }).notNull(), windowStart: timestamp("window_start", { withTimezone: true, mode: "string", precision: 3 }).notNull(), windowEnd: timestamp("window_end", { withTimezone: true, mode: "string", precision: 3 }).notNull(), continuationToken: text("continuation_token"), status: text("status").notNull(), lastRunId: text("last_run_id").references(() => sourceRuns.id), lastError: text("last_error"), createdAt: timestamp("created_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string", precision: 3 }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true, mode: "string", precision: 3 }),
}, (table) => [uniqueIndex("idx_ingestion_checkpoints_identity").on(table.sourceId, table.mode, table.coverageStart, table.coverageEnd), index("idx_ingestion_checkpoints_status_updated").on(table.status, table.updatedAt)]);

export const discoveryPages = pgTable('discovery_pages', {
  id:text('id').primaryKey(), sourceId:text('source_id').notNull().references(()=>sources.id), refs:jsonb('refs').notNull(), nextCursor:text('next_cursor'), createdAt:timestamp('created_at',{withTimezone:true,mode:'string'}).notNull().defaultNow(),
});
export const cveEnrichments = pgTable('cve_enrichments', {
  cveId:text('cve_id').notNull().references(()=>cves.id),sourceId:text('source_id').notNull().references(()=>sources.id),contentHash:text('content_hash').notNull(),payload:jsonb('payload').notNull(),sourceUrl:text('source_url').notNull(),sourceModifiedAt:timestamp('source_modified_at',{withTimezone:true,mode:'string'}),observedAt:timestamp('observed_at',{withTimezone:true,mode:'string'}).notNull(),sourceRunId:text('source_run_id').references(()=>sourceRuns.id),
}, t=>[primaryKey({columns:[t.cveId,t.sourceId,t.contentHash]}),index('cve_enrichments_latest').on(t.cveId,t.sourceId,t.observedAt)]);
export const enrichmentQueue = pgTable('enrichment_queue', {
  cveId:text('cve_id').notNull().references(()=>cves.id),sourceId:text('source_id').notNull().references(()=>sources.id),checkedAt:timestamp('checked_at',{withTimezone:true,mode:'string'}),retryAt:timestamp('retry_at',{withTimezone:true,mode:'string'}),failures:integer('failures').notNull().default(0),
},t=>[primaryKey({columns:[t.cveId,t.sourceId]})]);
export const vulncheckEntries = pgTable('vulncheck_entries', {
  cveId:text('cve_id').primaryKey().references(()=>cves.id),active:boolean('active').notNull(),dateAdded:timestamp('date_added',{withTimezone:true,mode:'string'}).notNull(),sourceModifiedAt:timestamp('source_modified_at',{withTimezone:true,mode:'string'}),payload:jsonb('payload').notNull(),contentHash:text('content_hash').notNull(),sourceRunId:text('source_run_id').references(()=>sourceRuns.id),firstObservedAt:timestamp('first_observed_at',{withTimezone:true,mode:'string'}).notNull(),lastObservedAt:timestamp('last_observed_at',{withTimezone:true,mode:'string'}).notNull(),removedAt:timestamp('removed_at',{withTimezone:true,mode:'string'}),
},t=>[index('vulncheck_entries_scope').on(t.active,t.dateAdded,t.cveId)]);
export const enrichmentUpdates = pgTable('enrichment_updates', {sourceId:text('source_id').primaryKey().references(()=>sources.id),completedAt:timestamp('completed_at',{withTimezone:true,mode:'string'}),windowStart:timestamp('window_start',{withTimezone:true,mode:'string'}),windowEnd:timestamp('window_end',{withTimezone:true,mode:'string'}),nextOffset:integer('next_offset').notNull().default(0)});
